services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: magrocaretech
      POSTGRES_USER: magrocaretech
      POSTGRES_PASSWORD: magrocaretech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: magrocaretech
      RABBITMQ_DEFAULT_PASS: magrocaretech
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: